package com.psplauncher.feature.settings.viewmodel

import android.content.Context
import android.content.Intent
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.psplauncher.core.domain.model.EmulatorProfile
import com.psplauncher.core.domain.model.Game
import com.psplauncher.core.domain.model.IntentType
import com.psplauncher.core.domain.repository.GameRepository
import kotlinx.coroutines.flow.first
import android.net.Uri
import com.psplauncher.feature.launcher.AppLaunchInspector
import com.psplauncher.feature.launcher.DetectableApp
import com.psplauncher.feature.launcher.EmulatorAutoConfigService
import com.psplauncher.feature.launcher.EmulatorIntentResolver
import com.psplauncher.feature.launcher.EmulatorProfileRepository
import com.psplauncher.feature.launcher.RetroArchCoreScanner
import com.psplauncher.core.data.repository.CoreInventory
import com.psplauncher.core.data.repository.RetroArchLink
import dagger.hilt.android.lifecycle.HiltViewModel
import dagger.hilt.android.qualifiers.ApplicationContext
import com.psplauncher.core.domain.model.PcRuntimes
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.util.UUID
import javax.inject.Inject

data class ProfileListItem(
    val id: String,
    val name: String,
    val packageName: String,
    val intentType: String,
    val isCustom: Boolean,
    val isAutoGenerated: Boolean = false,
    val isAvailable: Boolean = true,
    val userModified: Boolean = false,
    val autoSource: String? = null,
)

data class ProfileEditorState(
    val isNew: Boolean,
    val originalId: String?,
    val isAutoGenerated: Boolean = false,
    val name: String = "",
    val packageName: String = "",
    val activityClass: String = "",
    val intentType: IntentType = IntentType.ACTION_VIEW,
    val supportedPlatformIds: String = "",
    val mimeType: String = "",
    val useFileUri: Boolean = true,
    val useSafUri: Boolean = false,
    val customCommand: String = "",
    val notes: String = "",
    val isSaving: Boolean = false,
    val errorMessage: String? = null,

    val detectionNote: String? = null,

    val intentActionText: String = "",
    val intentExtrasText: String = "",
    val intentFlagsText: String = "",
    val intentCategoryText: String = "",
    val coreText: String = "",
    val extensionsText: String = "",
)

const val ADD_CUSTOM_EMULATOR_FOCUS_KEY = "add_custom_emulator"

enum class EmulatorTemplate(val label: String, val description: String) {
    VIEW_CONTENT("ACTION_VIEW + content:// URI", "Most modern emulators (Eden, Azahar, PPSSPP)"),
    VIEW_FILE("ACTION_VIEW + file:// path", "Older emulators that read a raw file path"),
    COMPONENT_BOOTPATH("COMPONENT + bootPath extra", "DuckStation / AetherSX2 style"),
    RETROARCH_CORE("RetroArch core (ROM + LIBRETRO)", "Set the core path in LIBRETRO"),
}

data class TestRom(
    val gameId: Long,
    val title: String,
    val platformId: String,
)

data class IntentPreview(
    val packageName: String,
    val activity: String?,
    val action: String,
    val mimeType: String?,
    val uriMode: String,
    val romRef: String,
    val extras: List<String>,
    val flags: List<String>,
)

data class TestLaunchState(
    val roms: List<TestRom> = emptyList(),
    val selectedRom: TestRom? = null,
    val preview: IntentPreview? = null,
    val resultMessage: String? = null,
    val isError: Boolean = false,
    val canLaunch: Boolean = false,
)

data class EmulatorsSettingsUiState(
    val installedProfiles: List<ProfileListItem> = emptyList(),
    val availableProfiles: List<ProfileListItem> = emptyList(),
    val customProfiles: List<ProfileListItem> = emptyList(),
    val editorState: ProfileEditorState? = null,

    val wizardApps: List<DetectableApp>? = null,
    val isInspecting: Boolean = false,

    val testLaunch: TestLaunchState? = null,
    val returnFocusKey: String? = null,
    val showResetConfirm: Boolean = false,
    val isResetting: Boolean = false,

    val retroArchLinked: Boolean = false,
    val retroArchCoreCount: Int? = null,

    val retroArchTreeHasNoCores: Boolean = false,
    val retroArchCores: List<String> = emptyList(),
    val isDetectingCores: Boolean = false,

    val pcRuntimes: List<String> = emptyList(),
)

@HiltViewModel
class EmulatorsSettingsViewModel @Inject constructor(
    private val profileRepository: EmulatorProfileRepository,
    private val appLaunchInspector: AppLaunchInspector,
    private val gameRepository: GameRepository,
    private val intentResolver: EmulatorIntentResolver,
    private val retroArchLink: RetroArchLink,
    private val autoConfig: EmulatorAutoConfigService,
    @ApplicationContext private val appContext: Context,
) : ViewModel() {
    private val _uiState = MutableStateFlow(EmulatorsSettingsUiState())
    val uiState: StateFlow<EmulatorsSettingsUiState> = _uiState.asStateFlow()

    private var allProfiles: List<EmulatorProfile> = emptyList()

    private var testIntent: Intent? = null

    init {
        detectPcRuntimes()
        observeProfiles()
        refreshRetroArchStatus()
    }

    private fun refreshRetroArchStatus() {
        viewModelScope.launch { readRetroArchState() }
    }

    private suspend fun readRetroArchState() {
        val inventory = retroArchLink.inventory()

        val cores = RetroArchCoreScanner.coresFor("com.retroarch", inventory.coreFiles).map { it.name }
        _uiState.update {
            it.copy(
                isDetectingCores   = false,
                retroArchLinked    = inventory is CoreInventory.Verified || inventory is CoreInventory.EmptyTree,
                retroArchCoreCount = if (inventory is CoreInventory.Unlinked) null else inventory.coreFiles.size,
                retroArchTreeHasNoCores = inventory is CoreInventory.EmptyTree,
                retroArchCores     = cores,
            )
        }
    }

    fun linkRetroArch(treeUri: Uri) {
        _uiState.update { it.copy(isDetectingCores = true) }
        viewModelScope.launch {
            retroArchLink.save(treeUri)
            autoConfig.runOnStartup()
            readRetroArchState()
        }
    }

    fun redetectRetroArchCores() {
        if (!_uiState.value.retroArchLinked) return
        _uiState.update { it.copy(isDetectingCores = true) }
        viewModelScope.launch {
            autoConfig.runOnStartup()
            readRetroArchState()
        }
    }

    fun unlinkRetroArch() {
        viewModelScope.launch {
            retroArchLink.clear()
            autoConfig.runOnStartup()
            _uiState.update {
                it.copy(
                    retroArchLinked = false,
                    retroArchCoreCount = null,
                    retroArchTreeHasNoCores = false,
                    retroArchCores = emptyList(),
                )
            }
        }
    }

    private fun detectPcRuntimes() {
        viewModelScope.launch {
            val installed = withContext(Dispatchers.IO) {
                runCatching {
                    appContext.packageManager.getInstalledPackages(0).mapNotNull { pkg ->
                        val name = pkg.packageName
                        when {
                            name == PcRuntimes.WINLATOR_FAMILY || name.startsWith("${PcRuntimes.WINLATOR_FAMILY}.") ->
                                appContext.packageManager.getApplicationLabel(pkg.applicationInfo!!).toString()
                            else -> PcRuntimes.PACKAGES[name]
                        }
                    }
                }.getOrDefault(emptyList()).distinct().sorted()
            }
            _uiState.update { it.copy(pcRuntimes = installed) }
        }
    }

    private fun observeProfiles() {
        viewModelScope.launch {
            profileRepository.profiles.collect { all ->
                allProfiles = all
                val installed = profileRepository.getInstalledProfiles()
                    .filterNot { it.autoSource == "retroarch-core" || it.packageName.contains("retroarch", ignoreCase = true) || it.name.contains("retroarch", ignoreCase = true) }
                    .dedupedByPackage()
                val custom    = all.filter { it.isCustom && !it.isAutoGenerated }
                val available = all.filter { p ->
                    !p.isCustom && !p.isAutoGenerated &&
                        p.autoSource != "retroarch-core" &&
                        !p.packageName.contains("retroarch", ignoreCase = true) &&
                        !p.name.contains("retroarch", ignoreCase = true) &&
                        installed.none { it.packageName == p.packageName }
                }
                _uiState.update {
                    it.copy(
                        installedProfiles = installed.map { p -> p.toListItem() },
                        availableProfiles = available.map { p -> p.toListItem() },
                        customProfiles    = custom.map { p -> p.toListItem() },
                    )
                }
            }
        }
    }

    private fun List<EmulatorProfile>.dedupedByPackage(): List<EmulatorProfile> =
        groupBy { it.packageName }
            .map { (_, sharing) -> sharing.firstOrNull { !it.isAutoGenerated } ?: sharing.first() }

            .toList()

    fun openEditor(profileId: String?) {
        val profile = profileId?.let { id -> allProfiles.firstOrNull { it.id == id } }
        _uiState.update {
            it.copy(
                returnFocusKey = profileId ?: ADD_CUSTOM_EMULATOR_FOCUS_KEY,
                editorState    = if (profile != null) editorStateFor(profile, isNew = false, detectionNote = null)
                                 else ProfileEditorState(isNew = true, originalId = null),
            )
        }
    }

    fun startAddEmulatorWizard() {
        _uiState.update { it.copy(returnFocusKey = ADD_CUSTOM_EMULATOR_FOCUS_KEY, isInspecting = true) }
        viewModelScope.launch {
            val apps = withContext(Dispatchers.IO) { appLaunchInspector.listLaunchableApps() }
            _uiState.update { it.copy(wizardApps = apps, isInspecting = false) }
        }
    }

    fun selectWizardApp(packageName: String) {
        _uiState.update { it.copy(isInspecting = true) }
        viewModelScope.launch {
            val suggestion = withContext(Dispatchers.IO) { appLaunchInspector.suggestForPackage(packageName) }
            _uiState.update {
                it.copy(
                    wizardApps = null,
                    isInspecting = false,
                    editorState = editorStateFor(suggestion.profile, isNew = true, detectionNote = suggestion.note),
                )
            }
        }
    }

    fun cancelWizard() {
        _uiState.update { it.copy(wizardApps = null, isInspecting = false) }
    }

    private fun editorStateFor(profile: EmulatorProfile, isNew: Boolean, detectionNote: String?) =
        ProfileEditorState(
            isNew                = isNew,
            originalId           = if (isNew) null else profile.id,
            isAutoGenerated      = profile.isAutoGenerated,
            name                 = profile.name,
            packageName          = profile.packageName,
            activityClass        = profile.activityClass ?: "",
            intentType           = profile.intentType,
            supportedPlatformIds = profile.supportedPlatformIds.joinToString(","),
            mimeType             = profile.mimeType ?: "",
            useFileUri           = profile.useFileUri,
            useSafUri            = profile.useSafUri,
            customCommand        = profile.customCommand ?: "",
            notes                = profile.notes ?: "",
            detectionNote        = detectionNote,
            intentActionText     = profile.intentAction ?: "",
            intentExtrasText     = extrasToText(profile.intentExtras, profile.intentBoolExtras),
            intentFlagsText      = profile.intentFlags.joinToString(", "),
            intentCategoryText   = profile.intentCategory ?: "",
            coreText             = profile.coreMap.values.firstOrNull() ?: "",
            extensionsText       = profile.supportedExtensions.joinToString(", "),
        )

    private fun extrasToText(extras: Map<String, String>, bools: Map<String, Boolean>): String =
        buildList {
            extras.forEach { (k, v) -> add("$k=$v") }
            bools.forEach { (k, v) -> add("$k=$v") }
        }.joinToString("\n")

    private fun parseExtras(text: String): Pair<Map<String, String>, Map<String, Boolean>> {
        val strings = linkedMapOf<String, String>()
        val booleans = linkedMapOf<String, Boolean>()
        text.lineSequence().forEach { line ->
            val t = line.trim()
            val eq = t.indexOf('=')
            if (eq <= 0) return@forEach
            val key = t.substring(0, eq).trim()
            val value = t.substring(eq + 1).trim()
            when (value.lowercase()) {
                "true"  -> booleans[key] = true
                "false" -> booleans[key] = false
                else    -> strings[key] = value
            }
        }
        return strings to booleans
    }

    private fun parseCsv(text: String): List<String> =
        text.split(",", "\n").map { it.trim() }.filter { it.isNotEmpty() }

    fun startTestLaunch() {
        if (_uiState.value.editorState == null) return
        viewModelScope.launch {
            val roms = withContext(Dispatchers.IO) {
                gameRepository.observeGamesOnly().first()
                    .filter { !it.romPath.isNullOrBlank() }
                    .map { TestRom(it.id, it.displayTitle, it.platformId) }
                    .sortedBy { it.title.lowercase() }
            }
            _uiState.update { it.copy(testLaunch = TestLaunchState(roms = roms)) }
        }
    }

    fun selectTestRom(gameId: Long) {
        val editor = _uiState.value.editorState ?: return
        val test = _uiState.value.testLaunch ?: return
        val rom = test.roms.firstOrNull { it.gameId == gameId } ?: return
        viewModelScope.launch {
            val game = withContext(Dispatchers.IO) { gameRepository.getById(gameId) }
            if (game == null) {
                _uiState.update { it.copy(testLaunch = test.copy(selectedRom = rom, resultMessage = "Could not load that ROM.", isError = true)) }
                return@launch
            }
            val profile = editor.draftProfile()
            val preview = buildPreview(profile, game)
            val result = withContext(Dispatchers.IO) { intentResolver.resolve(game, profile) }
            result.fold(
                onSuccess = { intent ->
                    testIntent = intent
                    _uiState.update { it.copy(testLaunch = test.copy(
                        selectedRom = rom, preview = preview,
                        resultMessage = "Resolves OK — press Launch Now to try it.",
                        isError = false, canLaunch = true,
                    )) }
                },
                onFailure = { e ->
                    testIntent = null
                    _uiState.update { it.copy(testLaunch = test.copy(
                        selectedRom = rom, preview = preview,
                        resultMessage = mapLaunchError(e), isError = true, canLaunch = false,
                    )) }
                },
            )
        }
    }

    fun launchTest() {
        val intent = testIntent ?: return
        val test = _uiState.value.testLaunch ?: return
        runCatching {
            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            appContext.startActivity(intent)
        }.onSuccess {
            _uiState.update { it.copy(testLaunch = test.copy(resultMessage = "Launched — check the emulator.", isError = false)) }
        }.onFailure { e ->
            _uiState.update { it.copy(testLaunch = test.copy(resultMessage = mapLaunchError(e), isError = true, canLaunch = false)) }
        }
    }

    fun pickDifferentTestRom() {
        testIntent = null
        _uiState.update { it.copy(testLaunch = it.testLaunch?.copy(
            selectedRom = null, preview = null, resultMessage = null, isError = false, canLaunch = false,
        )) }
    }

    fun closeTestLaunch() {
        testIntent = null
        _uiState.update { it.copy(testLaunch = null) }
    }

    private fun ProfileEditorState.draftProfile(): EmulatorProfile {
        val platforms = parseCsv(supportedPlatformIds)
        val (extras, boolExtras) = parseExtras(intentExtrasText)
        val core = coreText.trim()
        return EmulatorProfile(
            id                   = originalId ?: "draft_test",
            name                 = name.trim().ifEmpty { packageName },
            packageName          = packageName.trim(),
            activityClass        = activityClass.trimToNull(),
            intentType           = intentType,
            supportedPlatformIds = platforms,
            mimeType             = mimeType.trimToNull(),
            useFileUri           = useFileUri,
            useSafUri            = useSafUri,
            customCommand        = customCommand.trimToNull(),
            intentExtras         = extras,
            intentBoolExtras     = boolExtras,
            intentAction         = intentActionText.trimToNull(),
            intentFlags          = parseCsv(intentFlagsText),
            intentCategory       = intentCategoryText.trimToNull(),
            coreMap              = if (core.isEmpty() || platforms.isEmpty()) emptyMap()
                                   else platforms.associateWith { core },
            supportedExtensions  = parseCsv(extensionsText),
            isCustom             = true,
        )
    }

    private fun buildPreview(profile: EmulatorProfile, game: Game): IntentPreview {
        val uriMode = when {
            profile.intentType == IntentType.CUSTOM_COMMAND -> "custom command"
            profile.useSafUri  -> "content:// (FileProvider, read granted)"
            profile.useFileUri -> "file:// (content:// on API 24+)"
            else               -> "content://"
        }
        val action = when (profile.intentType) {
            IntentType.ACTION_VIEW    -> "android.intent.action.VIEW"
            IntentType.COMPONENT      -> profile.intentAction ?: "android.intent.action.MAIN"
            IntentType.CUSTOM_COMMAND -> "(custom command)"
            IntentType.SHORTCUT       -> "(shortcut)"
        }
        val extras = buildList {
            profile.intentExtras.forEach { (k, v) -> add("$k = $v") }
            profile.intentBoolExtras.forEach { (k, v) -> add("$k = $v") }
        }
        return IntentPreview(
            packageName = profile.packageName,
            activity    = profile.activityClass,
            action      = action,
            mimeType    = profile.mimeType,
            uriMode     = uriMode,
            romRef      = game.romPath ?: game.packageName ?: "(none)",
            extras      = extras,
            flags       = profile.intentFlags,
        )
    }

    private fun mapLaunchError(e: Throwable): String {
        val msg = e.message.orEmpty()
        return when {
            e is android.content.ActivityNotFoundException ->
                "Activity not found or not exported. Check the activity name, or try ACTION_VIEW instead."
            e is SecurityException ->
                "Permission denied — the app rejected the ROM URI. Try toggling SAF (content://) vs file URI."
            msg.contains("not installed", ignoreCase = true)      -> msg
            msg.contains("ROM file not found", ignoreCase = true)  -> msg
            msg.contains("ROM path is required", ignoreCase = true) -> msg
            msg.contains("core", ignoreCase = true)                -> msg
            msg.contains("cannot open this ROM", ignoreCase = true) ->
                "$msg The app didn't accept this MIME type / URI mode — try the other URI mode."
            msg.isNotBlank()                                       -> msg
            else                                                  -> "Launch failed for an unknown reason."
        }
    }

    fun closeEditor() {
        _uiState.update { it.copy(editorState = null) }
    }

    fun updateEditorName(value: String)           = updateEditor { copy(name = value, errorMessage = null) }
    fun updateEditorPackageName(value: String)    = updateEditor { copy(packageName = value, errorMessage = null) }
    fun updateEditorActivityClass(value: String)  = updateEditor { copy(activityClass = value) }
    fun updateEditorIntentType(value: IntentType) = updateEditor { copy(intentType = value) }
    fun updateEditorPlatformIds(value: String)    = updateEditor { copy(supportedPlatformIds = value) }
    fun updateEditorMimeType(value: String)       = updateEditor { copy(mimeType = value) }
    fun updateEditorUseFileUri(value: Boolean)    = updateEditor { copy(useFileUri = value) }
    fun updateEditorUseSafUri(value: Boolean)     = updateEditor { copy(useSafUri = value) }
    fun updateEditorCustomCommand(value: String)  = updateEditor { copy(customCommand = value) }
    fun updateEditorNotes(value: String)          = updateEditor { copy(notes = value) }
    fun updateEditorIntentAction(value: String)   = updateEditor { copy(intentActionText = value) }
    fun updateEditorIntentExtras(value: String)   = updateEditor { copy(intentExtrasText = value) }
    fun updateEditorIntentFlags(value: String)    = updateEditor { copy(intentFlagsText = value) }
    fun updateEditorIntentCategory(value: String) = updateEditor { copy(intentCategoryText = value) }
    fun updateEditorCore(value: String)           = updateEditor { copy(coreText = value) }
    fun updateEditorExtensions(value: String)     = updateEditor { copy(extensionsText = value) }

    fun applyTemplate(template: EmulatorTemplate) = updateEditor {
        when (template) {
            EmulatorTemplate.VIEW_CONTENT -> copy(
                intentType = IntentType.ACTION_VIEW, mimeType = "application/octet-stream",
                useSafUri = true, useFileUri = false,
                intentExtrasText = "", intentActionText = "", intentFlagsText = "", errorMessage = null,
            )
            EmulatorTemplate.VIEW_FILE -> copy(
                intentType = IntentType.ACTION_VIEW, mimeType = "application/octet-stream",
                useSafUri = false, useFileUri = true,
                intentExtrasText = "", intentActionText = "", intentFlagsText = "", errorMessage = null,
            )
            EmulatorTemplate.COMPONENT_BOOTPATH -> copy(
                intentType = IntentType.COMPONENT, useSafUri = false, useFileUri = true,
                intentExtrasText = "bootPath={rom_path}", intentFlagsText = "CLEAR_TASK, CLEAR_TOP", errorMessage = null,
            )
            EmulatorTemplate.RETROARCH_CORE -> copy(
                intentType = IntentType.COMPONENT,
                activityClass = "com.retroarch.browser.retroactivity.RetroActivityFuture",
                intentExtrasText = "ROM={rom_path}\nLIBRETRO={core_path}", errorMessage = null,
            )
        }
    }

    private fun updateEditor(block: ProfileEditorState.() -> ProfileEditorState) {
        _uiState.update { state -> state.copy(editorState = state.editorState?.block()) }
    }

    fun saveEditorProfile() {
        val editor = _uiState.value.editorState ?: return
        if (editor.name.isBlank()) {
            updateEditor { copy(errorMessage = "Name is required") }
            return
        }
        if (editor.packageName.isBlank() && editor.intentType != IntentType.CUSTOM_COMMAND) {
            updateEditor { copy(errorMessage = "Package name is required") }
            return
        }
        updateEditor { copy(isSaving = true, errorMessage = null) }
        viewModelScope.launch {
            val existing = editor.originalId?.let { id -> allProfiles.firstOrNull { it.id == id } }
            val now = System.currentTimeMillis()
            val profile = editor.draftProfile().copy(
                id                   = editor.originalId ?: UUID.randomUUID().toString(),
                name                 = editor.name.trim(),
                notes                = editor.notes.trimToNull(),

                isAutoGenerated      = existing?.isAutoGenerated ?: false,
                autoSource           = existing?.autoSource,
                lastDetectedAt       = existing?.lastDetectedAt,
                userModified         = true,
                isAvailable          = existing?.isAvailable ?: true,
                createdAt            = existing?.createdAt ?: now,
                updatedAt            = now,
            )
            profileRepository.savePersistedProfile(profile)
            _uiState.update { it.copy(editorState = null) }
        }
    }

    fun deleteProfile(id: String) {
        viewModelScope.launch {
            profileRepository.deleteCustomProfile(id)
            _uiState.update { it.copy(editorState = null) }
        }
    }

    fun requestResetEmulatorConfig() {
        _uiState.update { it.copy(showResetConfirm = true) }
    }

    fun cancelResetEmulatorConfig() {
        _uiState.update { it.copy(showResetConfirm = false) }
    }

    fun confirmResetEmulatorConfig() {
        _uiState.update { it.copy(showResetConfirm = false, isResetting = true) }
        viewModelScope.launch {
            profileRepository.resetPersistedProfiles()
            _uiState.update { it.copy(isResetting = false) }
        }
    }

    private fun EmulatorProfile.toListItem() = ProfileListItem(
        id             = id,
        name           = name,
        packageName    = packageName,
        intentType     = intentType.name,
        isCustom       = isCustom,
        isAutoGenerated = isAutoGenerated,
        isAvailable    = isAvailable,
        userModified   = userModified,
        autoSource     = autoSource,
    )

    private fun String.trimToNull() = trim().ifEmpty { null }
}
