package com.psplauncher.feature.settings.viewmodel

import android.content.Context
import android.content.Intent
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.psplauncher.core.domain.model.EmulatorProfile
import com.psplauncher.core.domain.model.Game
import com.psplauncher.core.domain.model.IntentType
import com.psplauncher.core.domain.repository.GameRepository
import kotlinx.coroutines.flow.first
import android.net.Uri
import com.psplauncher.feature.launcher.AppLaunchInspector
import com.psplauncher.feature.launcher.DetectableApp
import com.psplauncher.feature.launcher.EmulatorAutoConfigService
import com.psplauncher.feature.launcher.EmulatorIntentResolver
import com.psplauncher.feature.launcher.EmulatorProfileRepository
import com.psplauncher.feature.launcher.RetroArchCoreScanner
import com.psplauncher.core.data.repository.CoreInventory
import com.psplauncher.core.data.repository.RetroArchLink
import dagger.hilt.android.lifecycle.HiltViewModel
import dagger.hilt.android.qualifiers.ApplicationContext
import com.psplauncher.core.domain.model.PcRuntimes
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.util.UUID
import javax.inject.Inject

data class ProfileListItem(
    val id: String,
    val name: String,
    val packageName: String,
    val intentType: String,
    val isCustom: Boolean,
    val isAutoGenerated: Boolean = false,
    val isAvailable: Boolean = true,
    val userModified: Boolean = false,
    val autoSource: String? = null,
)

data class ProfileEditorState(
    val isNew: Boolean,
    val originalId: String?,
    val isAutoGenerated: Boolean = false,
    val name: String = "",
    val packageName: String = "",
    val activityClass: String = "",
    val intentType: IntentType = IntentType.ACTION_VIEW,
    val supportedPlatformIds: String = "",  // comma-separated
    val mimeType: String = "",
    val useFileUri: Boolean = true,
    val useSafUri: Boolean = false,
    val customCommand: String = "",
    val notes: String = "",
    val isSaving: Boolean = false,
    val errorMessage: String? = null,
    // Wizard banner explaining detection confidence (null = plain edit).
    val detectionNote: String? = null,
    // ── Advanced launch fields (editable as text; parsed back to typed on save) ──
    val intentActionText: String = "",
    val intentExtrasText: String = "",      // one "key=value" per line; true/false → bool extras
    val intentFlagsText: String = "",       // comma-separated (CLEAR_TASK, CLEAR_TOP, NEW_TASK)
    val intentCategoryText: String = "",
    val coreText: String = "",              // single RetroArch core path applied to all platforms
    val extensionsText: String = "",        // comma-separated file extensions
)

const val ADD_CUSTOM_EMULATOR_FOCUS_KEY = "add_custom_emulator"

// Recommended launch-shape presets offered when auto-detection can't infer the settings.
enum class EmulatorTemplate(val label: String, val description: String) {
    VIEW_CONTENT("ACTION_VIEW + content:// URI", "Most modern emulators (Eden, Azahar, PPSSPP)"),
    VIEW_FILE("ACTION_VIEW + file:// path", "Older emulators that read a raw file path"),
    COMPONENT_BOOTPATH("COMPONENT + bootPath extra", "DuckStation / AetherSX2 style"),
    RETROARCH_CORE("RetroArch core (ROM + LIBRETRO)", "Set the core path in LIBRETRO"),
}

// ── Test launch (wizard step) ──────────────────────────────────────────────────

data class TestRom(
    val gameId: Long,
    val title: String,
    val platformId: String,
)

// Safe, user-readable summary of the intent the draft profile would fire.
data class IntentPreview(
    val packageName: String,
    val activity: String?,
    val action: String,
    val mimeType: String?,
    val uriMode: String,
    val romRef: String,
    val extras: List<String>,
    val flags: List<String>,
)

data class TestLaunchState(
    val roms: List<TestRom> = emptyList(),
    val selectedRom: TestRom? = null,
    val preview: IntentPreview? = null,
    val resultMessage: String? = null,
    val isError: Boolean = false,
    val canLaunch: Boolean = false,
)

data class EmulatorsSettingsUiState(
    val installedProfiles: List<ProfileListItem> = emptyList(),
    val availableProfiles: List<ProfileListItem> = emptyList(),
    val customProfiles: List<ProfileListItem> = emptyList(),
    val editorState: ProfileEditorState? = null,
    // Non-null while the "Add Custom Emulator" wizard is on its Pick-App step.
    val wizardApps: List<DetectableApp>? = null,
    val isInspecting: Boolean = false,
    // Non-null while testing a draft profile against a ROM.
    val testLaunch: TestLaunchState? = null,
    val returnFocusKey: String? = null,
    val showResetConfirm: Boolean = false,
    val isResetting: Boolean = false,
    // RetroArch core detection: null count = not linked (offering unverified curated cores);
    // a count = linked and this many installed cores were detected.
    val retroArchLinked: Boolean = false,
    val retroArchCoreCount: Int? = null,
    val retroArchCores: List<String> = emptyList(),
    val isDetectingCores: Boolean = false,
    // Installed Windows/PC runtimes, by display name. They take no ROM and have no profile to
    // edit — the screen lists them so "PFP doesn't know about GameNative" stops being the
    // reasonable conclusion from an Emulators screen that never mentions it.
    val pcRuntimes: List<String> = emptyList(),
)

@HiltViewModel
class EmulatorsSettingsViewModel @Inject constructor(
    private val profileRepository: EmulatorProfileRepository,
    private val appLaunchInspector: AppLaunchInspector,
    private val gameRepository: GameRepository,
    private val intentResolver: EmulatorIntentResolver,
    private val retroArchLink: RetroArchLink,
    private val autoConfig: EmulatorAutoConfigService,
    @ApplicationContext private val appContext: Context,
) : ViewModel() {

    private val _uiState = MutableStateFlow(EmulatorsSettingsUiState())
    val uiState: StateFlow<EmulatorsSettingsUiState> = _uiState.asStateFlow()

    private var allProfiles: List<EmulatorProfile> = emptyList()
    // Holds the built, launchable test intent (kept out of UI state — Intents aren't UI data).
    private var testIntent: Intent? = null

    init {
        detectPcRuntimes()
        observeProfiles()
        refreshRetroArchStatus()
    }

    // ── RetroArch core detection (SAF link) ────────────────────────────────────

    private fun refreshRetroArchStatus() {
        viewModelScope.launch { readRetroArchState() }
    }

    /**
     * Publishes what PFP actually knows about the installed cores. `retroArchLinked` tracks a live
     * grant specifically, so a [CoreInventory.Remembered] read still lists the user's cores while
     * reporting unlinked — which is what prompts the re-link without wiping the list first.
     */
    private suspend fun readRetroArchState() {
        val inventory = retroArchLink.inventory()
        val cores = RetroArchCoreScanner.coresFor("com.retroarch", inventory.coreFiles).map { it.name }
        _uiState.update {
            it.copy(
                isDetectingCores   = false,
                retroArchLinked    = inventory is CoreInventory.Verified || inventory is CoreInventory.EmptyTree,
                retroArchCoreCount = if (inventory is CoreInventory.Unlinked) null else inventory.coreFiles.size,
                retroArchCores     = cores,
            )
        }
    }

    /** User picked RetroArch's folder in the SAF tree picker: persist it and re-run detection so
     *  only installed cores are offered. */
    fun linkRetroArch(treeUri: Uri) {
        _uiState.update { it.copy(isDetectingCores = true) }
        viewModelScope.launch {
            retroArchLink.save(treeUri)
            autoConfig.runOnStartup()
            readRetroArchState()
        }
    }

    /** Re-scan the already-linked RetroArch folder (after the user downloads more cores). */
    fun redetectRetroArchCores() {
        if (!_uiState.value.retroArchLinked) return
        _uiState.update { it.copy(isDetectingCores = true) }
        viewModelScope.launch {
            autoConfig.runOnStartup()
            readRetroArchState()
        }
    }

    fun unlinkRetroArch() {
        viewModelScope.launch {
            retroArchLink.clear()
            autoConfig.runOnStartup()
            _uiState.update { it.copy(retroArchLinked = false, retroArchCoreCount = null, retroArchCores = emptyList()) }
        }
    }

    /**
     * Which Windows/PC runtimes are actually installed.
     *
     * Read once, not observed: the set of installed apps does not change while a settings screen
     * is open, and the alternative is a PackageManager query per recomposition.
     *
     * Winlator is matched by prefix because every fork renames itself (com.winlator.cmod and
     * friends); the rest are exact. Both rules come from [PcRuntimes], which is also what tags
     * these packages as emulators for the app drawer — one list, two readers.
     */
    private fun detectPcRuntimes() {
        viewModelScope.launch {
            val installed = withContext(Dispatchers.IO) {
                runCatching {
                    appContext.packageManager.getInstalledPackages(0).mapNotNull { pkg ->
                        val name = pkg.packageName
                        when {
                            name == PcRuntimes.WINLATOR_FAMILY || name.startsWith("${PcRuntimes.WINLATOR_FAMILY}.") ->
                                appContext.packageManager.getApplicationLabel(pkg.applicationInfo!!).toString()
                            else -> PcRuntimes.PACKAGES[name]
                        }
                    }
                }.getOrDefault(emptyList()).distinct().sorted()
            }
            _uiState.update { it.copy(pcRuntimes = installed) }
        }
    }

    private fun observeProfiles() {
        viewModelScope.launch {
            profileRepository.profiles.collect { all ->
                allProfiles = all
                val installed = profileRepository.getInstalledProfiles()
                    .filterNot { it.autoSource == "retroarch-core" || it.packageName.contains("retroarch", ignoreCase = true) || it.name.contains("retroarch", ignoreCase = true) }
                    .dedupedByPackage()
                val custom    = all.filter { it.isCustom && !it.isAutoGenerated }
                val available = all.filter { p ->
                    !p.isCustom && !p.isAutoGenerated &&
                        p.autoSource != "retroarch-core" &&
                        !p.packageName.contains("retroarch", ignoreCase = true) &&
                        !p.name.contains("retroarch", ignoreCase = true) &&
                        installed.none { it.packageName == p.packageName }
                }
                _uiState.update {
                    it.copy(
                        installedProfiles = installed.map { p -> p.toListItem() },
                        availableProfiles = available.map { p -> p.toListItem() },
                        customProfiles    = custom.map { p -> p.toListItem() },
                    )
                }
            }
        }
    }

    /**
     * One row per installed app.
     *
     * An app with a curated recipe AND an auto-detected profile produced two rows -- "PPSSPP" and
     * "PPSSPP  Auto", "Dolphin Emulator" and "Dolphin", "NetherSX2 / AetherSX2" twice -- which
     * reads as two copies of the emulator being installed. Both profiles are real and both stay
     * in the repository; this is only about what the list shows.
     *
     * The curated one wins. It is the verified launch recipe, it is what actually launches a
     * game, and the auto-detected draft exists to cover apps that have no curated entry. Where
     * only the draft exists it is shown, Auto badge and all, which is the case that badge is for.
     */
    private fun List<EmulatorProfile>.dedupedByPackage(): List<EmulatorProfile> =
        groupBy { it.packageName }
            .map { (_, sharing) -> sharing.firstOrNull { !it.isAutoGenerated } ?: sharing.first() }
            // groupBy keeps first-seen order; map over its values keeps it too, so the list stays
            // in whatever order getInstalledProfiles returned rather than jumping about on a
            // rescan.
            .toList()

    fun openEditor(profileId: String?) {
        val profile = profileId?.let { id -> allProfiles.firstOrNull { it.id == id } }
        _uiState.update {
            it.copy(
                returnFocusKey = profileId ?: ADD_CUSTOM_EMULATOR_FOCUS_KEY,
                editorState    = if (profile != null) editorStateFor(profile, isNew = false, detectionNote = null)
                                 else ProfileEditorState(isNew = true, originalId = null),
            )
        }
    }

    // ── Add Custom Emulator wizard ─────────────────────────────────────────────

    /** Step 1: present the controller-navigable list of installed apps to pick from. */
    fun startAddEmulatorWizard() {
        _uiState.update { it.copy(returnFocusKey = ADD_CUSTOM_EMULATOR_FOCUS_KEY, isInspecting = true) }
        viewModelScope.launch {
            val apps = withContext(Dispatchers.IO) { appLaunchInspector.listLaunchableApps() }
            _uiState.update { it.copy(wizardApps = apps, isInspecting = false) }
        }
    }

    /** Step 2: inspect the chosen app and open the editor pre-filled with the best-guess draft. */
    fun selectWizardApp(packageName: String) {
        _uiState.update { it.copy(isInspecting = true) }
        viewModelScope.launch {
            val suggestion = withContext(Dispatchers.IO) { appLaunchInspector.suggestForPackage(packageName) }
            _uiState.update {
                it.copy(
                    wizardApps = null,
                    isInspecting = false,
                    editorState = editorStateFor(suggestion.profile, isNew = true, detectionNote = suggestion.note),
                )
            }
        }
    }

    fun cancelWizard() {
        _uiState.update { it.copy(wizardApps = null, isInspecting = false) }
    }

    private fun editorStateFor(profile: EmulatorProfile, isNew: Boolean, detectionNote: String?) =
        ProfileEditorState(
            isNew                = isNew,
            originalId           = if (isNew) null else profile.id,
            isAutoGenerated      = profile.isAutoGenerated,
            name                 = profile.name,
            packageName          = profile.packageName,
            activityClass        = profile.activityClass ?: "",
            intentType           = profile.intentType,
            supportedPlatformIds = profile.supportedPlatformIds.joinToString(","),
            mimeType             = profile.mimeType ?: "",
            useFileUri           = profile.useFileUri,
            useSafUri            = profile.useSafUri,
            customCommand        = profile.customCommand ?: "",
            notes                = profile.notes ?: "",
            detectionNote        = detectionNote,
            intentActionText     = profile.intentAction ?: "",
            intentExtrasText     = extrasToText(profile.intentExtras, profile.intentBoolExtras),
            intentFlagsText      = profile.intentFlags.joinToString(", "),
            intentCategoryText   = profile.intentCategory ?: "",
            coreText             = profile.coreMap.values.firstOrNull() ?: "",
            extensionsText       = profile.supportedExtensions.joinToString(", "),
        )

    private fun extrasToText(extras: Map<String, String>, bools: Map<String, Boolean>): String =
        buildList {
            extras.forEach { (k, v) -> add("$k=$v") }
            bools.forEach { (k, v) -> add("$k=$v") }
        }.joinToString("\n")

    private fun parseExtras(text: String): Pair<Map<String, String>, Map<String, Boolean>> {
        val strings = linkedMapOf<String, String>()
        val booleans = linkedMapOf<String, Boolean>()
        text.lineSequence().forEach { line ->
            val t = line.trim()
            val eq = t.indexOf('=')
            if (eq <= 0) return@forEach
            val key = t.substring(0, eq).trim()
            val value = t.substring(eq + 1).trim()
            when (value.lowercase()) {
                "true"  -> booleans[key] = true
                "false" -> booleans[key] = false
                else    -> strings[key] = value
            }
        }
        return strings to booleans
    }

    private fun parseCsv(text: String): List<String> =
        text.split(",", "\n").map { it.trim() }.filter { it.isNotEmpty() }

    // ── Test launch ────────────────────────────────────────────────────────────

    /** Loads the user's scanned ROMs to pick a test target (controller-navigable list). */
    fun startTestLaunch() {
        if (_uiState.value.editorState == null) return
        viewModelScope.launch {
            val roms = withContext(Dispatchers.IO) {
                gameRepository.observeGamesOnly().first()
                    .filter { !it.romPath.isNullOrBlank() }
                    .map { TestRom(it.id, it.displayTitle, it.platformId) }
                    .sortedBy { it.title.lowercase() }
            }
            _uiState.update { it.copy(testLaunch = TestLaunchState(roms = roms)) }
        }
    }

    /** Builds the intent from the current draft + chosen ROM, shows a preview, and reports whether
     *  it resolves. Does NOT launch yet — the user confirms with [launchTest]. */
    fun selectTestRom(gameId: Long) {
        val editor = _uiState.value.editorState ?: return
        val test = _uiState.value.testLaunch ?: return
        val rom = test.roms.firstOrNull { it.gameId == gameId } ?: return
        viewModelScope.launch {
            val game = withContext(Dispatchers.IO) { gameRepository.getById(gameId) }
            if (game == null) {
                _uiState.update { it.copy(testLaunch = test.copy(selectedRom = rom, resultMessage = "Could not load that ROM.", isError = true)) }
                return@launch
            }
            val profile = editor.draftProfile()
            val preview = buildPreview(profile, game)
            val result = withContext(Dispatchers.IO) { intentResolver.resolve(game, profile) }
            result.fold(
                onSuccess = { intent ->
                    testIntent = intent
                    _uiState.update { it.copy(testLaunch = test.copy(
                        selectedRom = rom, preview = preview,
                        resultMessage = "Resolves OK — press Launch Now to try it.",
                        isError = false, canLaunch = true,
                    )) }
                },
                onFailure = { e ->
                    testIntent = null
                    _uiState.update { it.copy(testLaunch = test.copy(
                        selectedRom = rom, preview = preview,
                        resultMessage = mapLaunchError(e), isError = true, canLaunch = false,
                    )) }
                },
            )
        }
    }

    fun launchTest() {
        val intent = testIntent ?: return
        val test = _uiState.value.testLaunch ?: return
        runCatching {
            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            appContext.startActivity(intent)
        }.onSuccess {
            _uiState.update { it.copy(testLaunch = test.copy(resultMessage = "Launched — check the emulator.", isError = false)) }
        }.onFailure { e ->
            _uiState.update { it.copy(testLaunch = test.copy(resultMessage = mapLaunchError(e), isError = true, canLaunch = false)) }
        }
    }

    fun pickDifferentTestRom() {
        testIntent = null
        _uiState.update { it.copy(testLaunch = it.testLaunch?.copy(
            selectedRom = null, preview = null, resultMessage = null, isError = false, canLaunch = false,
        )) }
    }

    fun closeTestLaunch() {
        testIntent = null
        _uiState.update { it.copy(testLaunch = null) }
    }

    private fun ProfileEditorState.draftProfile(): EmulatorProfile {
        val platforms = parseCsv(supportedPlatformIds)
        val (extras, boolExtras) = parseExtras(intentExtrasText)
        val core = coreText.trim()
        return EmulatorProfile(
            id                   = originalId ?: "draft_test",
            name                 = name.trim().ifEmpty { packageName },
            packageName          = packageName.trim(),
            activityClass        = activityClass.trimToNull(),
            intentType           = intentType,
            supportedPlatformIds = platforms,
            mimeType             = mimeType.trimToNull(),
            useFileUri           = useFileUri,
            useSafUri            = useSafUri,
            customCommand        = customCommand.trimToNull(),
            intentExtras         = extras,
            intentBoolExtras     = boolExtras,
            intentAction         = intentActionText.trimToNull(),
            intentFlags          = parseCsv(intentFlagsText),
            intentCategory       = intentCategoryText.trimToNull(),
            coreMap              = if (core.isEmpty() || platforms.isEmpty()) emptyMap()
                                   else platforms.associateWith { core },
            supportedExtensions  = parseCsv(extensionsText),
            isCustom             = true,
        )
    }

    private fun buildPreview(profile: EmulatorProfile, game: Game): IntentPreview {
        val uriMode = when {
            profile.intentType == IntentType.CUSTOM_COMMAND -> "custom command"
            profile.useSafUri  -> "content:// (FileProvider, read granted)"
            profile.useFileUri -> "file:// (content:// on API 24+)"
            else               -> "content://"
        }
        val action = when (profile.intentType) {
            IntentType.ACTION_VIEW    -> "android.intent.action.VIEW"
            IntentType.COMPONENT      -> profile.intentAction ?: "android.intent.action.MAIN"
            IntentType.CUSTOM_COMMAND -> "(custom command)"
            IntentType.SHORTCUT       -> "(shortcut)"
        }
        val extras = buildList {
            profile.intentExtras.forEach { (k, v) -> add("$k = $v") }
            profile.intentBoolExtras.forEach { (k, v) -> add("$k = $v") }
        }
        return IntentPreview(
            packageName = profile.packageName,
            activity    = profile.activityClass,
            action      = action,
            mimeType    = profile.mimeType,
            uriMode     = uriMode,
            romRef      = game.romPath ?: game.packageName ?: "(none)",
            extras      = extras,
            flags       = profile.intentFlags,
        )
    }

    // Maps resolver failures and startActivity exceptions to the spec's actionable error cases.
    private fun mapLaunchError(e: Throwable): String {
        val msg = e.message.orEmpty()
        return when {
            e is android.content.ActivityNotFoundException ->
                "Activity not found or not exported. Check the activity name, or try ACTION_VIEW instead."
            e is SecurityException ->
                "Permission denied — the app rejected the ROM URI. Try toggling SAF (content://) vs file URI."
            msg.contains("not installed", ignoreCase = true)      -> msg
            msg.contains("ROM file not found", ignoreCase = true)  -> msg
            msg.contains("ROM path is required", ignoreCase = true) -> msg
            msg.contains("core", ignoreCase = true)                -> msg   // missing RetroArch core
            msg.contains("cannot open this ROM", ignoreCase = true) ->
                "$msg The app didn't accept this MIME type / URI mode — try the other URI mode."
            msg.isNotBlank()                                       -> msg
            else                                                  -> "Launch failed for an unknown reason."
        }
    }

    fun closeEditor() {
        _uiState.update { it.copy(editorState = null) }
    }

    fun updateEditorName(value: String)           = updateEditor { copy(name = value, errorMessage = null) }
    fun updateEditorPackageName(value: String)    = updateEditor { copy(packageName = value, errorMessage = null) }
    fun updateEditorActivityClass(value: String)  = updateEditor { copy(activityClass = value) }
    fun updateEditorIntentType(value: IntentType) = updateEditor { copy(intentType = value) }
    fun updateEditorPlatformIds(value: String)    = updateEditor { copy(supportedPlatformIds = value) }
    fun updateEditorMimeType(value: String)       = updateEditor { copy(mimeType = value) }
    fun updateEditorUseFileUri(value: Boolean)    = updateEditor { copy(useFileUri = value) }
    fun updateEditorUseSafUri(value: Boolean)     = updateEditor { copy(useSafUri = value) }
    fun updateEditorCustomCommand(value: String)  = updateEditor { copy(customCommand = value) }
    fun updateEditorNotes(value: String)          = updateEditor { copy(notes = value) }
    fun updateEditorIntentAction(value: String)   = updateEditor { copy(intentActionText = value) }
    fun updateEditorIntentExtras(value: String)   = updateEditor { copy(intentExtrasText = value) }
    fun updateEditorIntentFlags(value: String)    = updateEditor { copy(intentFlagsText = value) }
    fun updateEditorIntentCategory(value: String) = updateEditor { copy(intentCategoryText = value) }
    fun updateEditorCore(value: String)           = updateEditor { copy(coreText = value) }
    fun updateEditorExtensions(value: String)     = updateEditor { copy(extensionsText = value) }

    // Recommended templates — quick presets for undetected apps. Each fills the launch shape;
    // the user then sets package/activity/platforms.
    fun applyTemplate(template: EmulatorTemplate) = updateEditor {
        when (template) {
            EmulatorTemplate.VIEW_CONTENT -> copy(
                intentType = IntentType.ACTION_VIEW, mimeType = "application/octet-stream",
                useSafUri = true, useFileUri = false,
                intentExtrasText = "", intentActionText = "", intentFlagsText = "", errorMessage = null,
            )
            EmulatorTemplate.VIEW_FILE -> copy(
                intentType = IntentType.ACTION_VIEW, mimeType = "application/octet-stream",
                useSafUri = false, useFileUri = true,
                intentExtrasText = "", intentActionText = "", intentFlagsText = "", errorMessage = null,
            )
            EmulatorTemplate.COMPONENT_BOOTPATH -> copy(
                intentType = IntentType.COMPONENT, useSafUri = false, useFileUri = true,
                intentExtrasText = "bootPath={rom_path}", intentFlagsText = "CLEAR_TASK, CLEAR_TOP", errorMessage = null,
            )
            EmulatorTemplate.RETROARCH_CORE -> copy(
                intentType = IntentType.COMPONENT,
                activityClass = "com.retroarch.browser.retroactivity.RetroActivityFuture",
                intentExtrasText = "ROM={rom_path}\nLIBRETRO={core_path}", errorMessage = null,
            )
        }
    }

    private fun updateEditor(block: ProfileEditorState.() -> ProfileEditorState) {
        _uiState.update { state -> state.copy(editorState = state.editorState?.block()) }
    }

    fun saveEditorProfile() {
        val editor = _uiState.value.editorState ?: return
        if (editor.name.isBlank()) {
            updateEditor { copy(errorMessage = "Name is required") }
            return
        }
        if (editor.packageName.isBlank() && editor.intentType != IntentType.CUSTOM_COMMAND) {
            updateEditor { copy(errorMessage = "Package name is required") }
            return
        }
        updateEditor { copy(isSaving = true, errorMessage = null) }
        viewModelScope.launch {
            val existing = editor.originalId?.let { id -> allProfiles.firstOrNull { it.id == id } }
            val now = System.currentTimeMillis()
            val profile = editor.draftProfile().copy(
                id                   = editor.originalId ?: UUID.randomUUID().toString(),
                name                 = editor.name.trim(),
                notes                = editor.notes.trimToNull(),
                // Preserve auto-gen metadata; mark as user-modified so auto-config skips it.
                isAutoGenerated      = existing?.isAutoGenerated ?: false,
                autoSource           = existing?.autoSource,
                lastDetectedAt       = existing?.lastDetectedAt,
                userModified         = true,
                isAvailable          = existing?.isAvailable ?: true,
                createdAt            = existing?.createdAt ?: now,
                updatedAt            = now,
            )
            profileRepository.savePersistedProfile(profile)
            _uiState.update { it.copy(editorState = null) }
        }
    }

    fun deleteProfile(id: String) {
        viewModelScope.launch {
            profileRepository.deleteCustomProfile(id)
            _uiState.update { it.copy(editorState = null) }
        }
    }

    fun requestResetEmulatorConfig() {
        _uiState.update { it.copy(showResetConfirm = true) }
    }

    fun cancelResetEmulatorConfig() {
        _uiState.update { it.copy(showResetConfirm = false) }
    }

    fun confirmResetEmulatorConfig() {
        _uiState.update { it.copy(showResetConfirm = false, isResetting = true) }
        viewModelScope.launch {
            profileRepository.resetPersistedProfiles()
            _uiState.update { it.copy(isResetting = false) }
        }
    }

    private fun EmulatorProfile.toListItem() = ProfileListItem(
        id             = id,
        name           = name,
        packageName    = packageName,
        intentType     = intentType.name,
        isCustom       = isCustom,
        isAutoGenerated = isAutoGenerated,
        isAvailable    = isAvailable,
        userModified   = userModified,
        autoSource     = autoSource,
    )

    private fun String.trimToNull() = trim().ifEmpty { null }
}
