package com.psplauncher.core.domain.model

import kotlinx.serialization.Serializable

@Serializable
data class EmulatorProfile(
    val id: String,
    val name: String,
    val packageName: String,
    val activityClass: String? = null,
    val intentType: IntentType,
    val supportedPlatformIds: List<String>,
    val intentExtras: Map<String, String> = emptyMap(),
    val intentBoolExtras: Map<String, Boolean> = emptyMap(),

    val intentArrayExtras: Map<String, List<String>> = emptyMap(),
    val intentAction: String? = null,
    val intentFlags: List<String> = emptyList(),
    val intentCategory: String? = null,

    val attachRomData: Boolean = false,
    val coreMap: Map<String, String> = emptyMap(),
    val mimeType: String? = null,
    val useFileUri: Boolean = true,
    val useSafUri: Boolean = false,
    val customCommand: String? = null,
    val minVersionCode: Int? = null,
    val notes: String? = null,

    val supportedExtensions: List<String> = emptyList(),
    val createdAt: Long? = null,
    val updatedAt: Long? = null,
    val isCustom: Boolean = false,

    val isAutoGenerated: Boolean = false,
    val autoSource: String? = null,
    val lastDetectedAt: Long? = null,
    val userModified: Boolean = false,
    val isAvailable: Boolean = true,
)

@Serializable
enum class IntentType {
    ACTION_VIEW,
    COMPONENT,
    SHORTCUT,
    CUSTOM_COMMAND,
}

object LaunchTemplate {
    const val ROM_PATH    = "{rom_path}"
    const val ROM_URI     = "{rom_uri}"
    const val ROM_NAME    = "{rom_name}"
    const val ROM_DIR     = "{rom_dir}"
    const val CORE_PATH   = "{core_path}"
    const val CONFIG_PATH = "{config_path}"
    const val PACKAGE     = "{package}"
    const val PLATFORM    = "{platform}"
    const val TITLE_ID    = "{title_id}"
}
