package com.psplauncher.feature.launcher

import android.content.Context
import android.content.pm.PackageInfo
import androidx.test.core.app.ApplicationProvider
import com.psplauncher.core.data.repository.CoreInventory
import com.psplauncher.core.data.repository.RetroArchLink
import com.psplauncher.core.domain.model.EmulatorProfile
import com.psplauncher.core.domain.model.IntentType
import io.mockk.coEvery
import io.mockk.mockk
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.runBlocking
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.Shadows.shadowOf
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * Startup reconciliation between the catalog and persisted profiles. The critical behavior:
 * untouched auto-profiles must adopt corrected catalog recipes on upgrade, while anything
 * the user edited or created stays untouched.
 */
@RunWith(RobolectricTestRunner::class)
class EmulatorAutoConfigServiceTest {

    private val context: Context = ApplicationProvider.getApplicationContext()
    private val repository = EmulatorProfileRepository(
        context,
        Dispatchers.Unconfined,
        mockk(relaxed = true),
    )
    // Real link, no stored tree → CoreInventory.Unlinked → no RetroArch cores offered.
    private val service = EmulatorAutoConfigService(
        EmulatorDetector(context),
        repository,
        com.psplauncher.core.data.repository.RetroArchLink(context),
    )

    private fun installPackage(packageName: String) {
        shadowOf(context.packageManager)
            .installPackage(PackageInfo().apply { this.packageName = packageName })
    }

    /** A service whose RetroArch inventory is fixed, so each [CoreInventory] state is testable. */
    private fun serviceSeeing(state: CoreInventory): EmulatorAutoConfigService {
        val link = mockk<RetroArchLink>()
        coEvery { link.inventory() } returns state
        return EmulatorAutoConfigService(EmulatorDetector(context), repository, link)
    }

    private fun retroArchCore(fileName: String, platform: String) = EmulatorProfile(
        id                   = EmulatorDetector.retroarchCoreId(fileName),
        name                 = "RetroArch · $fileName",
        packageName          = "com.retroarch",
        activityClass        = EmulatorDetector.RETROARCH_ACTIVITY_CLASS,
        intentType           = IntentType.COMPONENT,
        supportedPlatformIds = listOf(platform),
        coreMap              = mapOf(platform to "/data/data/com.retroarch/cores/$fileName"),
        isAutoGenerated      = true,
        autoSource           = "retroarch-core",
        isAvailable          = true,
    )

    private suspend fun persistedById(id: String): EmulatorProfile =
        repository.getAllPersistedProfiles().first { it.id == id }

    @Test
    fun `untouched auto profile adopts the corrected catalog recipe`() = runBlocking {
        installPackage("com.github.stenzek.duckstation")
        val staleId = EmulatorDetector.autoId("com.github.stenzek.duckstation")
        repository.savePersistedProfile(
            EmulatorProfile(
                id = staleId,
                name = "DuckStation",
                packageName = "com.github.stenzek.duckstation",
                activityClass = "com.github.stenzek.duckstation.EmulationActivity",
                intentType = IntentType.COMPONENT,
                supportedPlatformIds = listOf("psx", "ps1"),
                intentExtras = mapOf("bootPath" to "{rom_path}"), // pre-fix raw-path recipe
                isAutoGenerated = true,
                createdAt = 1234L,
            )
        )

        service.runOnStartup()

        val refreshed = persistedById(staleId)
        assertEquals(
            "{rom_uri}", refreshed.intentExtras["bootPath"],
            "Stale recipe should be replaced by the current catalog recipe",
        )
        assertEquals(1234L, refreshed.createdAt, "Creation time must survive the refresh")
        assertTrue(refreshed.isAvailable)
        assertFalse(refreshed.userModified)
    }

    @Test
    fun `user modified auto profile is left untouched`() = runBlocking {
        installPackage("me.magnum.melonds")
        val id = EmulatorDetector.autoId("me.magnum.melonds")
        val edited = EmulatorProfile(
            id = id,
            name = "melonDS (my tweaks)",
            packageName = "me.magnum.melonds",
            activityClass = "me.magnum.melonds.ui.emulator.EmulatorActivity",
            intentType = IntentType.COMPONENT,
            supportedPlatformIds = listOf("nds"),
            intentExtras = mapOf("uri" to "{rom_uri}", "myCustomExtra" to "keep-me"),
            isAutoGenerated = true,
            userModified = true,
        )
        repository.savePersistedProfile(edited)

        service.runOnStartup()

        val after = persistedById(id)
        assertEquals("melonDS (my tweaks)", after.name)
        assertEquals("keep-me", after.intentExtras["myCustomExtra"])
    }

    @Test
    fun `custom profile is never reconciled against the catalog`() = runBlocking {
        val custom = EmulatorProfile(
            id = "custom_my_fork",
            name = "My Fork",
            packageName = "com.example.myfork",
            intentType = IntentType.ACTION_VIEW,
            supportedPlatformIds = listOf("psx"),
            isCustom = true,
        )
        repository.savePersistedProfile(custom)

        service.runOnStartup()

        val after = persistedById("custom_my_fork")
        assertEquals("My Fork", after.name)
        assertTrue(after.isAvailable, "Custom profiles must not be marked unavailable")
    }

    @Test
    fun `auto profile for an uninstalled emulator is marked unavailable`() = runBlocking {
        val id = EmulatorDetector.autoId("org.ppsspp.ppsspp")
        repository.savePersistedProfile(
            EmulatorProfile(
                id = id,
                name = "PPSSPP",
                packageName = "org.ppsspp.ppsspp",
                intentType = IntentType.ACTION_VIEW,
                supportedPlatformIds = listOf("psp"),
                isAutoGenerated = true,
                isAvailable = true,
            )
        )

        service.runOnStartup()

        assertFalse(persistedById(id).isAvailable)
    }

    // Regression, the black-screen bug this whole change exists for. These two tests previously
    // asserted the OPPOSITE — that an unlinked RetroArch still offers a full curated core set — and
    // that fabricated set is exactly what shipped users onto cores they had never downloaded:
    // profiles persisted as available, winning the automatic default for every console without a
    // standalone emulator, launching RetroArch with a core path that did not exist.
    @Test
    fun `no retroarch profiles are offered without a core inventory`() {
        installPackage("com.retroarch")

        val profiles = EmulatorDetector(context).detect(CoreInventory.Unlinked)
            .filter { it.autoSource == "retroarch-core" }

        assertTrue(
            profiles.isEmpty(),
            "Unlinked RetroArch must offer no cores, got ${profiles.map { it.name }}",
        )
    }

    @Test
    fun `only cores present in the inventory are offered`() {
        installPackage("com.retroarch")
        val inventory = CoreInventory.Verified(
            setOf(
                "fceumm_libretro_android.so",   // NES
                "mgba_libretro_android.so",     // GB/GBC/GBA
                "notes.txt",                    // not a core
                "obscure_libretro_android.so",  // a core, but unmapped to any platform
            )
        )

        val profiles = EmulatorDetector(context).detect(inventory)
            .filter { it.autoSource == "retroarch-core" }

        assertEquals(2, profiles.size, "Only mapped, installed cores may become profiles")
        val platforms = profiles.flatMap { it.supportedPlatformIds }.toSet()
        assertTrue("nes" in platforms)
        assertTrue("gba" in platforms)
        assertFalse("snes" in platforms, "No SNES core is installed, so no SNES core may be offered")

        val nes = profiles.first { "nes" in it.supportedPlatformIds }
        assertEquals(
            "/data/data/com.retroarch/cores/fceumm_libretro_android.so",
            nes.intentExtras["LIBRETRO"],
            "LIBRETRO must name RetroArch's internal core path",
        )
        assertEquals(nes.intentExtras["LIBRETRO"], nes.coreMap["nes"])
    }

    // The read-only invariant: an inventory that cannot prove a core is present cannot prove it is
    // absent. Disabling one on a guess drops it from the launch pool, so without this a lost SAF
    // grant — a RetroArch reinstall is enough — would silently disable working consoles.
    @Test
    fun `an unverifiable inventory never disables a retroarch core`() = runBlocking {
        installPackage("com.retroarch")
        val core = retroArchCore("mgba_libretro_android.so", "gba")
        repository.savePersistedProfile(core)

        // A remembered set that no longer lists the core is stale, not evidence.
        serviceSeeing(CoreInventory.Remembered(setOf("fceumm_libretro_android.so"))).runOnStartup()
        assertTrue(persistedById(core.id).isAvailable, "A remembered inventory must not disable a core")

        serviceSeeing(CoreInventory.EmptyTree).runOnStartup()
        assertTrue(persistedById(core.id).isAvailable, "A wrong-folder link must not disable a core")

        serviceSeeing(CoreInventory.Unlinked).runOnStartup()
        assertTrue(persistedById(core.id).isAvailable, "An unlinked inventory must not disable a core")
    }

    @Test
    fun `a verified inventory does disable a core that is gone`() = runBlocking {
        installPackage("com.retroarch")
        val core = retroArchCore("snes9x_libretro_android.so", "snes")
        repository.savePersistedProfile(core)

        serviceSeeing(CoreInventory.Verified(setOf("mgba_libretro_android.so"))).runOnStartup()

        assertFalse(
            persistedById(core.id).isAvailable,
            "A live read that omits the core is proof it is gone",
        )
    }

    @Test
    fun `detector maps attachRomData through to the profile`() {
        installPackage("dev.eden.eden_emulator")

        val eden = EmulatorDetector(context).detect()
            .first { it.packageName == "dev.eden.eden_emulator" }

        assertEquals(IntentType.COMPONENT, eden.intentType)
        assertEquals("android.nfc.action.TECH_DISCOVERED", eden.intentAction)
        assertTrue(eden.attachRomData, "attachRomData lost between catalog and profile")
        assertEquals("org.yuzu.yuzu_emu.activities.EmulationActivity", eden.activityClass)
    }
}
