package com.psplauncher.feature.launcher

import com.psplauncher.core.data.repository.CoreInventory
import com.psplauncher.core.data.repository.RetroArchLink
import timber.log.Timber
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class EmulatorAutoConfigService @Inject constructor(
    private val detector: EmulatorDetector,
    private val repository: EmulatorProfileRepository,
    private val retroArchLink: RetroArchLink,
) {

    suspend fun runOnStartup() {
        val inventory = retroArchLink.inventory()
        val existing = repository.getAllPersistedProfiles()
        val detected = detector.detect(inventory)
        val now = System.currentTimeMillis()
        var added = 0
        var refreshed = 0

        for (profile in detected) {
            val match = existing.firstOrNull { it.id == profile.id }
            when {
                match == null -> {
                    // No entry yet — create auto-generated entry
                    repository.savePersistedProfile(profile)
                    added++
                }
                match.isAutoGenerated && !match.userModified -> {
                    // Auto entry not touched by user — adopt the freshly detected profile so
                    // catalog recipe corrections reach existing installs, keeping creation time.
                    repository.savePersistedProfile(
                        profile.copy(createdAt = match.createdAt, lastDetectedAt = now)
                    )
                    refreshed++
                }
                // isCustom or userModified: user owns this entry, leave it untouched
            }
        }

        // Mark auto-generated entries whose emulator is no longer installed.
        //
        // A standalone emulator is checked against the PackageManager, which always answers. A
        // RetroArch core can only be checked against the SAF inventory, which frequently cannot —
        // and an inventory that cannot prove a core is present cannot prove it is absent either.
        // Marking one unavailable from a guess is not a cosmetic error: an unavailable profile is
        // dropped from the launch pool, so a lost SAF grant (a RetroArch reinstall is enough) would
        // silently disable consoles the user had working. So availability for RetroArch cores moves
        // only on an authoritative read; otherwise their current state is left exactly as it is.
        val canJudgeCores = inventory.isAuthoritative
        val detectedIds = detected.map { it.id }.toSet()
        var markedUnavailable = 0
        var heldPendingVerification = 0
        for (entry in existing) {
            if (!entry.isAutoGenerated || entry.userModified) continue
            if (entry.id in detectedIds || !entry.isAvailable) continue
            if (entry.autoSource == "retroarch-core" && !canJudgeCores) {
                heldPendingVerification++
                continue
            }
            repository.savePersistedProfile(entry.copy(isAvailable = false))
            markedUnavailable++
        }

        Timber.i(
            "EmulatorAutoConfig: +$added new, $refreshed refreshed, $markedUnavailable marked " +
                "unavailable, $heldPendingVerification held (unverified ${inventory::class.simpleName} " +
                "core inventory)"
        )
        if (inventory is CoreInventory.EmptyTree) {
            Timber.w("RetroArch is linked but its granted folder holds no cores — likely the wrong folder")
        }
    }
}
