package com.psplauncher.feature.launcher

import com.psplauncher.core.data.repository.CoreInventory
import com.psplauncher.core.data.repository.RetroArchLink
import timber.log.Timber
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class EmulatorAutoConfigService @Inject constructor(
    private val detector: EmulatorDetector,
    private val repository: EmulatorProfileRepository,
    private val retroArchLink: RetroArchLink,
) {
    suspend fun runOnStartup() {
        val inventory = retroArchLink.inventory()
        val existing = repository.getAllPersistedProfiles()
        val detected = detector.detect(inventory)
        val now = System.currentTimeMillis()
        var added = 0
        var refreshed = 0

        for (profile in detected) {
            val match = existing.firstOrNull { it.id == profile.id }
            when {
                match == null -> {
                    repository.savePersistedProfile(profile)
                    added++
                }
                match.isAutoGenerated && !match.userModified -> {
                    repository.savePersistedProfile(
                        profile.copy(createdAt = match.createdAt, lastDetectedAt = now)
                    )
                    refreshed++
                }
            }
        }

        val canJudgeCores = inventory.isAuthoritative
        val detectedIds = detected.map { it.id }.toSet()
        var markedUnavailable = 0
        var heldPendingVerification = 0
        for (entry in existing) {
            if (!entry.isAutoGenerated || entry.userModified) continue
            if (entry.id in detectedIds || !entry.isAvailable) continue
            if (entry.autoSource == "retroarch-core" && !canJudgeCores) {
                heldPendingVerification++
                continue
            }
            repository.savePersistedProfile(entry.copy(isAvailable = false))
            markedUnavailable++
        }

        Timber.i(
            "EmulatorAutoConfig: +$added new, $refreshed refreshed, $markedUnavailable marked " +
                "unavailable, $heldPendingVerification held (unverified ${inventory::class.simpleName} " +
                "core inventory)"
        )
        if (inventory is CoreInventory.EmptyTree) {
            Timber.w("RetroArch is linked but its granted folder holds no cores — likely the wrong folder")
        }
    }
}
