package com.psplauncher.feature.launcher

import android.content.Context
import android.content.pm.PackageManager
import com.psplauncher.core.data.repository.CoreInventory
import com.psplauncher.core.domain.model.EmulatorProfile
import com.psplauncher.core.domain.model.IntentType
import dagger.hilt.android.qualifiers.ApplicationContext
import timber.log.Timber
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class EmulatorDetector @Inject constructor(
    @ApplicationContext private val context: Context,
) {
    fun detect(inventory: CoreInventory = CoreInventory.Unlinked): List<EmulatorProfile> {
        val pm = context.packageManager
        val results = mutableListOf<EmulatorProfile>()
        val now = System.currentTimeMillis()

        for (known in KnownEmulatorCatalog.entries) {
            val installedPkg = known.packageNames.firstOrNull { pkg ->
                try { pm.getPackageInfo(pkg, 0); true }
                catch (_: PackageManager.NameNotFoundException) { false }
            } ?: continue

            results += EmulatorProfile(
                id                   = autoId(installedPkg),
                name                 = known.suggestedName,
                packageName          = installedPkg,
                intentType           = known.intentType,
                activityClass        = known.activityClass,
                supportedPlatformIds = known.platformIds,
                intentExtras         = known.intentExtras,
                intentBoolExtras     = known.intentBoolExtras,
                intentArrayExtras    = known.intentArrayExtras,
                intentAction         = known.intentAction,
                intentFlags          = known.intentFlags,
                intentCategory       = known.intentCategory,
                attachRomData        = known.attachRomData,
                mimeType             = known.mimeType,
                useSafUri            = known.useSafUri,
                isAutoGenerated      = true,
                autoSource           = "auto-detected",
                lastDetectedAt       = now,
                isAvailable          = true,
            )
        }

        val retroarchPkg = RetroArchCoreScanner.RETROARCH_PACKAGES.firstOrNull { pkg ->
            try { pm.getPackageInfo(pkg, 0); true }
            catch (_: PackageManager.NameNotFoundException) { false }
        }
        if (retroarchPkg != null) {
            val cores = RetroArchCoreScanner.coresFor(retroarchPkg, inventory.coreFiles)
            Timber.i(
                "RetroArch detected ($retroarchPkg): ${cores.size} core profiles " +
                    "from a ${inventory::class.simpleName} inventory"
            )
            for (core in cores) {
                results += EmulatorProfile(
                    id                   = retroarchCoreId(core.fileName),
                    name                 = "RetroArch · ${core.name}",
                    packageName          = retroarchPkg,
                    intentType           = IntentType.COMPONENT,
                    activityClass        = RETROARCH_ACTIVITY_CLASS,
                    supportedPlatformIds = core.platformIds,
                    intentExtras         = retroArchExtras(retroarchPkg, core.absolutePath),
                    coreMap              = core.platformIds.associateWith { core.absolutePath },
                    notes                = "${core.name} core (detected installed in RetroArch).",
                    isAutoGenerated      = true,
                    autoSource           = "retroarch-core",
                    lastDetectedAt       = now,
                    isAvailable          = true,
                )
            }
        }

        Timber.i(
            "EmulatorDetector: ${results.size} profiles detected " +
            "(${results.count { it.autoSource == "retroarch-core" }} RetroArch cores)"
        )
        return results
    }

    private fun retroArchExtras(packageName: String, corePath: String): Map<String, String> {
        val app = runCatching { context.packageManager.getApplicationInfo(packageName, 0) }.getOrNull()
        val dataDir = app?.dataDir
        val apk = app?.sourceDir
        val sdcard = android.os.Environment.getExternalStorageDirectory().absolutePath

        val external = "$sdcard/Android/data/$packageName/files"
        return buildMap {
            put("ROM", "{rom_path}")
            put("LIBRETRO", corePath)
            put("CONFIGFILE", "$external/retroarch.cfg")
            put("EXTERNAL", external)
            put("SDCARD", sdcard)

            if (dataDir != null) put("DATADIR", dataDir)
            if (apk != null) put("APK", apk)
        }
    }

    companion object {
        const val RETROARCH_ACTIVITY_CLASS = "com.retroarch.browser.retroactivity.RetroActivityFuture"

        fun autoId(packageName: String): String =
            "auto_${packageName.replace('.', '_')}"

        fun retroarchCoreId(fileName: String): String =
            "auto_retroarch_${fileName.removeSuffix(".so").replace('-', '_')}"
    }
}
