"""
Generates the matched catbar_* vector set.

    python3 tools/caticons/generate.py        # from the repo root

Writes core/core-ui/src/main/res/drawable/catbar_*.xml, and an SVG of each alongside it in
$SP (or /tmp) so the result can be rasterised and looked at before it ships:

    for f in $SP/icons/*.svg; do rsvg-convert -w 128 -h 128 "$f" -o "${f%.svg}.png"; done

This exists because the set it replaced had never been drawn together — the source PNGs ranged
from 128px to 1050px and the weights did not agree. Path data by hand drifts the same way, so the
geometry is computed here instead, from one description per glyph, and the preview is generated
from the SAME strings that go into the XML. What gets looked at is what ships.

The two glyphs NOT here, catbar_library.xml and catbar_recent.xml, were hand-drawn earlier on the
same 24x24 grid and already matched; they are left alone rather than redrawn for the sake of it.
Studio copies live in studio/src/main/resources/xmb/ and must be replaced in the same commit -
see StudioIconSet.
"""
import math, os, subprocess

def circle(cx, cy, r):
    return f"M{cx-r:.2f},{cy:.2f} A{r:.2f},{r:.2f} 0 1,1 {cx+r-0.001:.3f},{cy:.2f} A{r:.2f},{r:.2f} 0 1,1 {cx-r:.2f},{cy:.2f} Z"

def ellipse(cx, cy, rx, ry):
    return f"M{cx-rx:.2f},{cy:.2f} A{rx:.2f},{ry:.2f} 0 1,1 {cx+rx-0.001:.3f},{cy:.2f} A{rx:.2f},{ry:.2f} 0 1,1 {cx-rx:.2f},{cy:.2f} Z"

def rect(x, y, w, h):
    return f"M{x:.2f},{y:.2f} H{x+w:.2f} V{y+h:.2f} H{x:.2f} Z"

def star(cx, cy, outer, inner, points=5):
    pts = []
    for i in range(points * 2):
        r = outer if i % 2 == 0 else inner
        a = -math.pi / 2 + i * math.pi / points
        pts.append(f"{cx + r*math.cos(a):.2f},{cy + r*math.sin(a):.2f}")
    return "M" + " L".join(pts) + " Z"

# Each icon: list of (pathData, fillType). fillType "evenOdd" cuts holes.
ICONS = {}

# ── Game: a Memory Stick Duo, which is what the PSP's Game column actually shows.
ICONS["catbar_games"] = [(
    " ".join([
        "M9.8,2.6 L18.0,2.6 L18.0,21.4 L6.0,21.4 L6.0,6.4 Z",
        rect(8.0, 16.8, 1.7, 3.0),
        rect(11.15, 16.8, 1.7, 3.0),
        rect(14.3, 16.8, 1.7, 3.0),
    ]), "evenOdd")]

# ── Music: a beamed pair of eighth notes.
ICONS["catbar_music"] = [
    ("M9.9,5.2 L19.4,3.0 L19.4,5.9 L9.9,8.1 Z", "nonZero"),
    (rect(9.9, 5.2, 1.6, 11.2), "nonZero"),
    (rect(17.8, 3.0, 1.6, 9.9), "nonZero"),
    (ellipse(8.2, 16.8, 2.7, 2.2), "nonZero"),
    (ellipse(16.1, 13.3, 2.7, 2.2), "nonZero"),
]

# ── Video: a strip of film. Sprockets and the play triangle are cut out of one body.
ICONS["catbar_video"] = [(
    " ".join([
        rect(2.6, 5.4, 18.8, 13.2),
        rect(4.1, 6.9, 1.8, 1.8), rect(4.1, 10.2, 1.8, 1.8), rect(4.1, 13.5, 1.8, 1.8),
        rect(18.1, 6.9, 1.8, 1.8), rect(18.1, 10.2, 1.8, 1.8), rect(18.1, 13.5, 1.8, 1.8),
        "M10.3,8.9 L15.4,12.0 L10.3,15.1 Z",
    ]), "evenOdd")]

# ── Photo: a framed picture with a hill and a sun.
ICONS["catbar_photos"] = [
    (" ".join([rect(2.6, 4.8, 18.8, 14.4), rect(4.4, 6.6, 15.2, 10.8)]), "evenOdd"),
    ("M5.6,16.2 L10.0,10.4 L12.9,14.0 L15.0,11.5 L18.4,16.2 Z", "nonZero"),
    (circle(8.0, 9.2, 1.45), "nonZero"),
]

# ── Network: a globe. Outer ring, equator, meridian — each its own ring.
ICONS["catbar_network"] = [
    (circle(12, 12, 9.0) + " " + circle(12, 12, 7.4), "evenOdd"),
    (rect(4.0, 11.2, 16.0, 1.6), "nonZero"),
    (ellipse(12, 12, 4.4, 9.0) + " " + ellipse(12, 12, 3.0, 7.4), "evenOdd"),
]

# ── Settings: a toolbox, which is the PSP's own Settings glyph.
ICONS["catbar_settings"] = [
    ("M9.5,3.0 H14.5 A1.3,1.3 0 0,1 15.8,4.3 V6.6 H14.0 V4.8 H10.0 V6.6 H8.2 V4.3 A1.3,1.3 0 0,1 9.5,3.0 Z", "nonZero"),
    (" ".join([rect(2.6, 7.2, 18.8, 13.0), rect(10.7, 11.6, 2.6, 4.2)]), "evenOdd"),
]

# ── Favorites: a bare star. The old one carried a rounded backing plate nothing else had.
ICONS["catbar_favorites"] = [(star(12, 12.4, 9.2, 3.9), "nonZero")]

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
  Category-bar glyph: {desc}

  Part of the matched catbar_* set. Every glyph in it is drawn on the same 24x24 grid at the same
  optical weight, as flat white fills with no backing plate, so PortalIcon's tint and the
  legibility matte behave identically across the whole bar. The set it replaced was borrowed from
  the xmb-menu-es-de theme and had never been drawn together: the source images ranged from 128px
  to 1050px, the weights did not agree, and Favorites alone sat on a rounded plate.

  Generated by tools/caticons/generate.py - edit the glyph there and re-run, rather than
  editing the path data here by hand.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="96dp"
    android:height="96dp"
    android:viewportWidth="24"
    android:viewportHeight="24"
    android:tint="#FFFFFFFF">
"""

DESCS = {
    "catbar_games": "the Game column. A Memory Stick Duo, which is what the PSP's own Game icon is -\n  the set this replaced used a modern gamepad.",
    "catbar_music": "the Music column. A beamed pair of eighth notes; the glyph this\n  replaced was a folder, which said nothing about music.",
    "catbar_video": "the Video column. A strip of film with a play mark cut out of it.",
    "catbar_photos": "the Photo column. A framed picture with a hill and a sun.",
    "catbar_network": "the Network column. A globe with an equator and a meridian.",
    "catbar_settings": "the Settings column. A toolbox, which is the PSP's own Settings glyph.",
    "catbar_favorites": "Favorites. A bare star - the glyph this replaced was the only one\n  on the bar carrying a rounded backing plate.",
}

out_xml = "core/core-ui/src/main/res/drawable"
preview_dir = os.environ.get("SP", "/tmp") + "/icons"
os.makedirs(preview_dir, exist_ok=True)

for name, paths in ICONS.items():
    body = ""
    svg_body = ""
    for d, ft in paths:
        ft_attr = '\n        android:fillType="evenOdd"' if ft == "evenOdd" else ""
        body += f'    <path\n        android:fillColor="#FFFFFFFF"{ft_attr}\n        android:pathData="{d}" />\n'
        rule = ' fill-rule="evenodd"' if ft == "evenOdd" else ""
        svg_body += f'  <path fill="#FFFFFF"{rule} d="{d}"/>\n'
    with open(f"{out_xml}/{name}.xml", "w") as f:
        f.write(HEADER.format(desc=DESCS[name]) + body + "</vector>\n")
    svg = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="128" height="128">\n{svg_body}</svg>\n'
    with open(f"{preview_dir}/{name}.svg", "w") as f:
        f.write(svg)

print("wrote", len(ICONS), "vectors")
